fix: resolve issue when updating or adding content type (#998)
* fix: resolve issue when updating or adding content type with draft enabled

fix: resolve Meilisearch issue with draftAndPublish enabled

When updating or adding an item with draftAndPublish enabled, the item is removed from Meilisearch, and the following error occurs:

error: Meilisearch could not add entry with id: 9: Transaction query already complete

This issue is described in https://github.com/meilisearch/strapi-plugin-meilisearch/issues/997. The item should update correctly without errors when draftAndPublish is enabled.

* test (lifecycle): implemend test for afterCreate, afterCreateMany, afterUpdate, afterUpdateMany, afterDelete and afterDeleteMany

* cleanup: eslint issues

---------

Co-authored-by: ratorik <ratorikdeveloper@gmail.com>